### ISSUE TITLE
Latest elftools version causes tests to fail during CI/CD

### ISSUE THREAD

**Issue by Alan-Jowett** [iovisor/ubpf#100]
https://app.travis-ci.com/github/Alan-Jowett/ubpf/jobs/564087024
```
======================================================================
ERROR: test_elf.test_datafiles('elf/wrong-version.data',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alanjo/.local/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/alanjo/ubpf/test_framework/test_elf.py", line 180, in check_datafile
    elf = generate_elf(data['pyelf'])
  File "/home/alanjo/ubpf/test_framework/test_elf.py", line 167, in generate_elf
    return serialize(parts)
  File "/home/alanjo/ubpf/test_framework/test_elf.py", line 157, in serialize
    data = serializer(part)
  File "/home/alanjo/.local/lib/python3.8/site-packages/elftools/construct/core.py", line 204, in build
    self.build_stream(obj, stream)
  File "/home/alanjo/.local/lib/python3.8/site-packages/elftools/construct/core.py", line 211, in build_stream
    self._build(obj, stream, Container())
  File "/home/alanjo/.local/lib/python3.8/site-packages/elftools/construct/core.py", line 666, in _build
    sc._build(subobj, stream, context)
  File "/home/alanjo/.local/lib/python3.8/site-packages/elftools/construct/core.py", line 1074, in _build
    self.subcon._build(obj, stream2, context)
  File "/home/alanjo/.local/lib/python3.8/site-packages/elftools/construct/core.py", line 664, in _build
    subobj = getattr(obj, sc.name)
AttributeError: 'Container' object has no attribute 'local'

----------------------------------------------------------------------
```

**Comment by matt-gretton-dann** [comment]
I think [this commit](https://github.com/iovisor/ubpf/pull/97/commits/bf0a6388b0d9c361449e01869df1ee3fab335299) should fix them - part of PR #97.
